/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JAB' at '2/02/16 15:38' with Gradle 2.10
 *
 * @author JAB, @date 2/02/16 15:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
