/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jabrena' at '6/03/16 15:46' with Gradle 2.4
 *
 * @author jabrena, @date 6/03/16 15:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
