/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jabrena' at '12/06/16 11:38' with Gradle 2.4
 *
 * @author jabrena, @date 12/06/16 11:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
